;
; confbridge.conf - Conferencing profiles (app_confbridge)
;

[default_user]
type = user
announce_join_leave = yes
music_on_hold_when_empty = yes
dsp_drop_silence = yes

[admin_user]
type = user
admin = yes
marked = yes

[default_bridge]
type = bridge
max_members = 50
record_conference = no

[default_menu]
type = menu
; DTMF in-conference controls
* = playback_and_continue
1 = toggle_mute
4 = decrease_listening_volume
6 = increase_listening_volume
7 = decrease_talking_volume
9 = increase_talking_volume
