version: '3.8'
name: voip-stack

services:
  drachtio-server:
    image: drachtio/drachtio-server
    container_name: drachtio-server
    ports:
      - "9022:9022" # Drachtio control socket
      - "5060:5060/udp" # SIP UDP
      - "5060:5060/tcp" # SIP TCP
      - "5065:5065/tcp" # SIP WebSocket (for browser SIP.js)
    environment:
      - DRACHTIO_SECRET=siprocks
      - DRACHTIO_LISTEN=tcp,udp
      - DRACHTIO_PORT=9022
      - DRACHTIO_EXTERNAL_IP=auto
    restart: unless-stopped
    networks:
      - voipnet
    volumes:
      - ./drachtio-server/config/drachtio.conf.xml:/etc/drachtio.conf.xml
  drachtio-freeswitch:
    image: drachtio/drachtio-freeswitch-mrf
    container_name: drachtio-freeswitch
    ports:
      - "8021:8021"
      - "16384-16403:16384-16403/udp"
    environment:
      - FREESWITCH_EVENT_SOCKET_PASSWORD=JambonzR0ck$
    volumes:
      - ./drachtio/drachtio-freeswitch-mrf/sounds:/usr/share/freeswitch/sounds
    networks:
      - voipnet
    restart: unless-stopped

  # freeswitch:
  #   image: ghcr.io/patrickbaus/freeswitch-docker
  #   container_name: freeswitch
  #   restart: always
  #   ports:
  #     - "5070:5060/udp" # SIP UDP
  #     - "5080:5080/tcp" # SIP TCP (optional)
  #     - "8022:8021" # ESL (Event Socket)
  #     - "16384-32768:16384-32768/udp" # RTP ports
  #   cap_add:
  #     # Enable RT features
  #     - SYS_NICE
  #   networks:
  #     - voipnet
  #   volumes:
  #     - ./freeswitch/configs:/etc/freeswitch
  #     - ./freeswitch/logs/:/var/log/freeswitch/
  #     - ./freeswitch_sounds:/usr/share/freeswitch/sounds
  # asterisk:
  #   image: andrius/asterisk:latest
  #   ports:
  #     - "5060:5060/udp"
  #     - "10000-20000:10000-20000/udp"
  #   volumes:
  #     - ./asterisk/config:/etc/asterisk
  #     - ./asterisk:/var/lib/asterisk
  #   restart: unless-stopped

  # freeswitch:
  #   image: safarov/freeswitch
  #   container_name: freeswitch
  #   network_mode: host
  #   environment:
  #     SOUND_RATES: "8000:16000"
  #     SOUND_TYPES: "music:en-us-callie"
  #   volumes:
  #     - ./freeswitch_sounds:/usr/share/freeswitch/sounds
  #     - ./freeswitch_configs:/etc/freeswitch
  #     - freeswitch-recordings:/usr/local/freeswitch/recordings
  #   restart: unless-stopped
 
 
networks:
  voipnet:
    driver: bridge

volumes:
  freeswitch-sounds:
  freeswitch-recordings:
  tele-conf: 
