-- Default demo IVR on extension 5000.
--
-- Extension 5000 is already classified as an IVR route in the SIP runtime
-- (dialplan.service.ts IVR_PATTERN), so a call to 5000 lands on the IVR handler.
-- This seed gives 5000 a ready-to-demo visual flow so anyone can call it and
-- experience the interpreter (greeting -> menu -> play / voicemail / hangup)
-- without first authoring a flow in the dashboard.
--
-- Idempotent: keyed on the unique `extension`, so re-applying refreshes the same
-- row instead of creating duplicates. Edit by adding a NEW migration (history is
-- immutable) — do not edit this file once applied.

INSERT INTO ivr_flows (id, name, extension, enabled, graph)
VALUES (
  'demo-ivr-5000',
  'Demo IVR',
  '5000',
  TRUE,
  '{
    "nodes": [
      {
        "id": "n_start",
        "type": "start",
        "data": {
          "kind": "start",
          "label": "Start",
          "extension": "5000",
          "greeting": {
            "mode": "tts",
            "text": "Welcome to the Enjoys Voice demo. This is an automated voice menu."
          }
        }
      },
      {
        "id": "n_menu",
        "type": "menu",
        "data": {
          "kind": "menu",
          "label": "Main Menu",
          "prompt": {
            "mode": "tts",
            "text": "Press 1 to hear about Enjoys Voice. Press 2 to leave a voicemail. Press 0 to end the call."
          },
          "validDigits": "120",
          "tries": 3,
          "timeoutMs": 7000,
          "invalidPrompt": {
            "mode": "tts",
            "text": "Sorry, that was not a valid choice."
          },
          "options": [
            { "id": "opt1", "digit": "1", "label": "About" },
            { "id": "opt2", "digit": "2", "label": "Voicemail" },
            { "id": "opt0", "digit": "0", "label": "Hang up" }
          ]
        }
      },
      {
        "id": "n_about",
        "type": "play",
        "data": {
          "kind": "play",
          "label": "About",
          "prompt": {
            "mode": "tts",
            "text": "Enjoys Voice is a cloud calling platform with voicemail, interactive voice menus, and conferencing."
          },
          "bargeIn": true
        }
      },
      {
        "id": "n_vm",
        "type": "voicemail",
        "data": {
          "kind": "voicemail",
          "label": "Voicemail",
          "mailbox": "5000",
          "maxSeconds": 60,
          "greeting": {
            "mode": "tts",
            "text": "Please leave your message after the beep. Press the pound key when you are finished."
          }
        }
      },
      {
        "id": "n_bye",
        "type": "hangup",
        "data": { "kind": "hangup", "label": "Goodbye" }
      }
    ],
    "edges": [
      { "id": "e_start_menu",    "source": "n_start", "target": "n_menu", "sourceHandle": null },
      { "id": "e_menu_about",    "source": "n_menu",  "target": "n_about", "sourceHandle": "opt1" },
      { "id": "e_menu_vm",       "source": "n_menu",  "target": "n_vm",    "sourceHandle": "opt2" },
      { "id": "e_menu_bye",      "source": "n_menu",  "target": "n_bye",   "sourceHandle": "opt0" },
      { "id": "e_menu_fallback", "source": "n_menu",  "target": "n_bye",   "sourceHandle": null },
      { "id": "e_about_menu",    "source": "n_about", "target": "n_menu",  "sourceHandle": null }
    ]
  }'::jsonb
)
ON CONFLICT (extension) DO UPDATE
  SET id         = EXCLUDED.id,
      name       = EXCLUDED.name,
      enabled    = EXCLUDED.enabled,
      graph      = EXCLUDED.graph,
      updated_at = NOW();
