-- Seed a default "Standard" rate plan with a starter set of destination rates.
--
-- Without at least one rate plan the rating engine is a no-op: every outbound
-- call goes unrated (cost 0), so the admin dashboard's Total Spend / Avg Cost
-- cards read 0.00 even on a busy system. This seed gives a fresh install a
-- working price book out of the box; operators edit it from the Rates tab.
--
-- Why a guarded CTE instead of ON CONFLICT: rate_plans.id is a SERIAL, so
-- hard-coding an id would desync the sequence and collide with later API
-- inserts. Instead we seed the plan only when the table is EMPTY, and attach the
-- starter rates to exactly that newly-inserted plan via RETURNING — so an
-- operator who already configured their own plans (upgrade path) is never
-- touched, and the rates can't bind to a pre-existing plan. The migration ledger
-- runs this file once regardless; the empty-table guard is the safety net.
--
-- Idempotent: re-applying is a no-op once any plan exists. Edit by adding a NEW
-- migration (history is immutable) — do not edit this file once applied.

WITH seeded_plan AS (
  INSERT INTO rate_plans (name, currency, is_default, created_at, updated_at)
  SELECT 'Standard', 'USD', TRUE, NOW(), NOW()
  WHERE NOT EXISTS (SELECT 1 FROM rate_plans)
  RETURNING id
)
INSERT INTO rates (
  rate_plan_id, prefix, description,
  sell_per_min, buy_per_min, setup_fee,
  increment_secs, min_secs, created_at, updated_at
)
SELECT
  sp.id, v.prefix, v.description,
  v.sell_per_min, v.buy_per_min, v.setup_fee,
  v.increment_secs, v.min_secs, NOW(), NOW()
FROM seeded_plan sp
CROSS JOIN (VALUES
  ('1',   'United States & Canada', 0.01200, 0.00800, 0.00000, 60, 60),
  ('44',  'United Kingdom',         0.01500, 0.01000, 0.00000, 60, 60),
  ('91',  'India',                  0.01000, 0.00600, 0.00000, 60, 60),
  ('61',  'Australia',              0.02000, 0.01400, 0.00000, 60, 60),
  ('49',  'Germany',                0.01800, 0.01200, 0.00000, 60, 60),
  ('971', 'United Arab Emirates',   0.08000, 0.06000, 0.00000, 60, 60)
) AS v(prefix, description, sell_per_min, buy_per_min, setup_fee, increment_secs, min_secs);
