-- Seed the self-hosted admin account.
--
-- A fresh install has no admin: trunk management and wallet top-ups are gated by
-- the ADMIN_EXTENSIONS allow-list (handler.requireAdmin checks the JWT
-- `extension` claim), and an account only becomes an admin when its extension is
-- listed there. This seed creates a single operator account so a self-hosting
-- admin can log in and manage trunks/billing out of the box. Pair it with
-- ADMIN_EXTENSIONS=9306373743 in the environment.
--
-- Password hashing: the Go login path verifies with golang.org/x/crypto/bcrypt,
-- which accepts pgcrypto's $2a$ output, so we hash in-SQL via
-- crypt(<plain>, gen_salt('bf', 10)). gen_salt makes each install's hash unique
-- and never stores the plaintext.
--
-- Idempotent: guarded by WHERE NOT EXISTS on the unique columns (extension,
-- username, mobile), so re-applying — or applying on a DB that already has this
-- account — is a no-op and never trips a unique violation. Edit by adding a NEW
-- migration (history is immutable) — do not edit this file once applied.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

WITH new_user AS (
  INSERT INTO users (extension, username, name, mobile, password, created_at, updated_at)
  SELECT '9306373743', '9306373743', 'Admin', '9306373743',
         crypt('Mullayam@123', gen_salt('bf', 10)), NOW(), NOW()
  WHERE NOT EXISTS (
    SELECT 1 FROM users
    WHERE extension = '9306373743' OR username = '9306373743' OR mobile = '9306373743'
  )
  RETURNING id, extension
)
INSERT INTO user_settings (
  user_id, extension, sounds_enabled, dtmf_enabled,
  caller_tune, ringtone, pstn_country_code, created_at, updated_at
)
SELECT nu.id, nu.extension, TRUE, TRUE,
       'caller_tune.wav', 'ringtone.wav', '+91', NOW(), NOW()
FROM new_user nu;
